window.sampleUsers = [
  {
    id: 1,
    picture: "./img/image1.jpg",
    fName: "Alice",
    lName: "Johnson",
    ageVal: "27",
    cityVal: "New York",
    positionVal: "Designer",
    salaryVal: "80000",
    sDateVal: "2022-01-15",
    emailVal: "alice.j@example.com"
  },
  {
    id: 2,
    picture: "./img/avatar.jpg",
    fName: "Bob",
    lName: "Smith",
    ageVal: "34",
    cityVal: "Los Angeles",
    positionVal: "Developer",
    salaryVal: "90000",
    sDateVal: "2021-05-21",
    emailVal: "bob.s@example.com"
  },
  {
    id: 3,
    picture: "./img/image2.jpg",
    fName: "Ethan",
    lName: "Rivera",
    ageVal: "34",
    cityVal: "Los Angeles",
    positionVal: "Software Engineer",
    salaryVal: "78500",
    sDateVal: "2020-02-23",
    emailVal: "ethan.rivera@example.com"
  },
  {
    id: 4,
    picture: "./img/avatar.jpg",
    fName: "Lucas",
    lName: "Bennett",
    ageVal: "38",
    cityVal: "Seattle",
    positionVal: "Data Scientist",
    salaryVal: "95000",
    sDateVal: "2024-08-02",
    emailVal: "lucas.bennett@example.com"
  },
  {
    id: 5,
    picture: "./img/image4.jpg",
    fName: "Isabella",
    lName: "Flores",
    ageVal: "33",
    cityVal: "Austin",
    positionVal: "Project Manager",
    salaryVal: "79300",
    sDateVal: "2022-05-07",
    emailVal: "	isabella.flores@example.com"
  },
  {
    id: 6,
    picture: "./img/image3.jpg",
    fName: "Zoe",
    lName: "Ramirez",
    ageVal: "35",
    cityVal: "Phoenix",
    positionVal: "Content Strategist",
    salaryVal: "56400",
    sDateVal: "2019-11-03",
    emailVal: "zoe.ramirez@example.com"
  },
  {
    id: 7,
    picture: "./img/avatar.jpg",
    fName: "Liam",
    lName: "Nguyen",
    ageVal: "29",
    cityVal: "Boston",
    positionVal: "Full-Stack Developer",
    salaryVal: "83700",
    sDateVal: "2023-01-22",
    emailVal: "liam.nguyen@example.com"
  },
  {
    id: 8,
    picture: "./img/avatar.jpg",
    fName: "Mia",
    lName: "Delgado",
    ageVal: "28",
    cityVal: "Chicago",
    positionVal: "UX Designer",
    salaryVal: "64200",
    sDateVal: "2025-01-12",
    emailVal: "mia.delgado@example.com"
  },
  {
    id: 9,
    picture: "./img/image5.jpg",
    fName: "Aria",
    lName: "Patel",
    ageVal: "35",
    cityVal: "San Diego",
    positionVal: "Business Analyst",
    salaryVal: "61750",
    sDateVal: "2023-06-19",
    emailVal: "aria.patel@example.com"
  },
  {
    id: 10,
    picture: "./img/avatar.jpg",
    fName: "Mason",
    lName: "Lee",
    ageVal: "31",
    cityVal: "Miami",
    positionVal: "Front-End Developer",
    salaryVal: "90000",
    sDateVal: "2024-12-23",
    emailVal: "mason.lee@example.com"
  },
  {
    id:11,
    picture: "./img/image6.jpg",
    fName: "Noah",
    lName: "Brooks",
    ageVal: "28",
    cityVal: "San Jose",
    positionVal: "QA Engineer",
    salaryVal: "70600",
    sDateVal: "2022-06-22",
    emailVal: "noah.brooks@example.com"
  },
  {
    id: 12,
    picture: "./img/avatar.jpg",
    fName: "Lily",
    lName: "Hoffman",
    ageVal: "40",
    cityVal: "Dallas",
    positionVal: "Social Media Manager",
    salaryVal: "58900",
    sDateVal: "2024-08-14",
    emailVal: "lily.hoffman@example.com"
  },
  {
    id: 13,
    picture: "./img/image7.jpg",
    fName: "James",
    lName: "Park",
    ageVal: "32",
    cityVal: "Delgado",
    positionVal: "Backend Developer",
    salaryVal: "92300",
    sDateVal: "2022-03-07",
    emailVal: "james.park@example.com"
  },
  {
    id: 14,
    picture: "./img/avatar.jpg",
    fName: "Grace",
    lName: "Kim",
    ageVal: "28",
    cityVal: "Philadelphia",
    positionVal: "Marketing Specialist",
    salaryVal: "60000",
    sDateVal: "2023-08-06",
    emailVal: "bob.s@example.com"
  },
  {
    id: 15,
    picture: "./img/avatar.jpg",
    fName: "Elijah",
    lName: "Morgan",
    ageVal: "30",
    cityVal: "Minneapolis",
    positionVal: "IT Support Specialist",
    salaryVal: "76200",
    sDateVal: "2019-02-17",
    emailVal: "elijah.morgan@example.com"
  },
];
